name: New Release (internal use only)
description: This template is used for tracking releases
title: "[RELEASE][PWABUILDER|VSCODE|STARTER|ETC] X.X"
labels: ["release-task"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - PWABuilder.com
        - VS Code extension
        - PWA Starter
        - Component
        - Docs
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      value: |

        This issue tracks the publishing progress for a release. It will get updated as tasks are completed.


        <!-- 
        This issue should only be created by a maintainer to track progress of a release. Link to sub-issues if approprite.

        IMPORTANT: Make sure the title of this issue includes the product name (pwabuilder/vscode/starter/component/etc)
        -->

        #### Code
          - [ ] Link to issue tracking board: {link_goes_here}
          - [ ] All P0s completed
          - [ ] PR submitted to main and approved
          - [ ] PR merged

        #### Design
          - [ ] Design reviewed and signed off

        #### Bug Bash
          - [ ] Bug bash scheduled

        #### Docs Release Notes
          - [ ] Authored and PR approved
          - [ ] PR merged

        #### Docs
          - [ ] Authored and PR approved
          - [ ] PR merged

        #### Blog Post
          - [ ] Authored and PR approved
          - [ ] PR merged

        #### Social
          - [ ] Tweeted
          - [ ] Discord updated
