# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Redesign Web App

on:
  push:
    branches:
      - redesign

env:
  NODE_VERSION: '14.x' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pwabuilder.azurecr.io/pwa-site-dev:redesign

      - name: Login
        run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}

      - name: Push
        run: docker push pwabuilder.azurecr.io/pwa-site-dev:redesigntest
